# Последняя версия docker-compose
version: '3.3'

# Создаем контейнер приложения
services:
  db:
    image: postgres:14.2
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ~/Projects/docker-volumes/voting
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
  adminer:
    image: adminer:4
    restart: always
    ports:
      - "8080:8080"
