export enum RepositoryNames
{
	USERS_REPOSITORY = 'USERS_REPOSITORY',
	VOTES_REPOSITORY = 'VOTES_REPOSITORY',
	VOTE_ANSWERS_REPOSITORY = 'VOTE_ANSWERS_REPOSITORY',
	VOTE_STATS_REPOSITORY = 'VOTE_STATS_REPOSITORY',
}
